### ISSUE TITLE
SPARQL Query Results XML Format Errata

### ISSUE THREAD

**Issue by afs** [w3c/sparql-results-xml#5]
From https://www.w3.org/2013/sparql-errata#rdf-sparql-XMLres

- [x] https://www.w3.org/2013/sparql-errata#errata-results-1 - Incorrect XML namespaces.
- [x] https://www.w3.org/2013/sparql-errata#errata-results-2 - xsi:schemaLocation should be a pair of URIs.

**Comment by domel** [comment]
Regarding the `2005` vs `2007` namespace. Which one do we choose to treat as the appropriate one? The examples in the doc are `2005` but the schemas are `2007`.

**Comment by rubensworks** [comment]
I believe the namespace `http://www.w3.org/2005/sparql-results#` is the desired one.

It may be just the `targetNamespace` in https://www.w3.org/2007/SPARQL/result.xsd that is incorrect, and may have to be updated to `http://www.w3.org/2005/sparql-results#`.

**Comment by rubensworks** [comment]
Now that #7 has been merged, the only thing that remains, is to update the links to the rnc, rng, and xsd files before this issue can be closed.
