### ISSUE TITLE
ITS namespace

### ISSUE THREAD

**Issue by afs** [w3c/sparql-results-xml#51]
All the examples are of the form:
```xml
<sparql xmlns="http://www.w3.org/2005/sparql-results#"
  xmlns:its="http://www.w3.org/2005/11/its" 
  its:version="2.0">
```
and the spec notes it is only needed if there are literals with base direction appearing in the results.

Writing a result set may be a streaming process - the contents aren't known when the `<sparql ...` start element is written, possibly leading to systems always adding `xmlns:its="http://www.w3.org/2005/11/its" its:version="2.0"`. 

The main problem with that is the transition impact - RDF 1.1 data but with added `its`. It shouldn't matter but it is a visible change.

It is also possible to write XML namespaces on other start elements to give an inline form:

```xml
    <binding name="x">
        <literal xml:lang="en" xmlns:its="http://www.w3.org/2005/11/its" its:version="2.0" its:dir="ltr">abc</literal>
    </binding>
```

then it only appears as needed but can become very verbose (compression would be good though).

**Comment by rubensworks** [comment]
Shall we add a note to make it explicit that the inline-form is also allowed, with an example?

**Comment by afs** [comment]
Yes
(I couldn't at the time when I raised the issue, because of juggling other PRs.)
